### PR TITLE
2.16.0 -> 2.16.1

### PR DESCRIPTION
**Pull request by ahuarte47**
Changes of migrating Geoserver 2.16.0 to new 2.16.1 version

### CODE REVIEW

**Comment by oscarfonts** [comment]
Thanks!

**Comment by ahuarte47** [comment]
Thanks @oscarfonts and congratulations for this amazing Docker of Geoserver.

**Comment by ahuarte47** [comment]
Ups, Geoserver 2.16.1 does not start properly, I get an error deploying to AWS and runing in Docker:

`"starting container process caused "exec: \"start.sh\": executable file not found in $PATH"`

Maybe can be betetr to revert this PR.

**Comment by oscarfonts** [comment]
It's not your fault, error us coming from a previous merge.
Issued #21.

**Comment by ahuarte47** [comment]
Great Oscar, thank you very much!

**Pull request merged**
